---
- name: example of template
  hosts: localhost
  become: yes
  gather_facts: no 
  vars:
    http_port: 8000
    https_port: 4443
    html_welcome_msg: "Hello world"
  
  tasks:
    - name: httpd is at the latest version
      ansible.builtin.dnf:
         name: httpd
         state: latest
    - name: write the httpd ports.conf config file
      ansible.builtin.template:
          src: templates/ports.conf.j2
          dest: /etc/httpd/ports.conf
    - name: write a bsic index.html file
      ansible.builtin.template:
          src: templates/index.html.j2
          dest: /var/www/html/index.html
      notify:
      - restart httpd
    - name: ensure that the httpd service is running
      ansible.builtin.service:
          name: httpd
          state: started

  handlers:
    - name: restart the httpd service
      ansible.builtin.service:
          name: httpd
          state: restarted
          