---
- name: Play to demonstrate the debug strategy
  hosts: localhost
  strategy: debug
  debugger: on_failed
  gather_facts: no
  vars:
    name: santhosh
  tasks:
    - name: Generate an error by referencing an undefined variable
      ansible.builtin.ping: data={{ mobile }}